### PR TITLE
refactoring code to prepare for multiprocessing

### PR DESCRIPTION
**Pull request by calledit**
Refactoring the text 2 audio part of the code in to separate classes for each engine.

This will clean up the code allot and make implementing multiprocessing very easy and clean.

The idea is to have a main class (Text2WaveFile) that all backend engines inherit from.
This way most of the code does not need to know what backend engine is being used.

### CODE REVIEW

**Comment by aedocw** [comment]
Thank you so much for all this work - it's so nice to see this mess of code cleaned up!

**Comment by calledit** [comment]
This can be merged now.
It's a good start, but more cleanup would still be nice.

Stuff that would be nice sometime in the future:

- move each engine to its own file with its own imports.
- Remove even more engine specific code from the main class.
- Don't place temp files in the main project folder.
- Use a proper HTML renderer, (like headless chromium) to get spacing and line breaks exactly right.
- Unclear what line 836 and 838 does..
- Somehow silence the torch warnings about loading unsafe models

That said; this is enough for now.
Adding multiprocessing should be easy now.

**Comment by aedocw** [comment]
I'm in solid agreement with the nice to haves for the future, all things that are needed!

Lines 836 and 838 were to address an issue I hit where one of the services returned an mp3 file while the other returned a wav file, so I think they needed to be handled differently by something in there.

I hit the following error in one of my tests:
```
ᐅ python3 epub2tts.py /tmp/testing.txt --xtts voices/adam-1.wav --model adamwhite --cover cover.jpg
Traceback (most recent call last): 
  File "/home/doc/epub2tts.py", line 1141, in <module>
    main()
  File "/home/doc/epub2tts.py", line 1128, in main
    mybook.read_book(
  File "/home/doc/epub2tts.py", line 776, in read_book
    engine_cl = XTTS(config)
  File "/home/doc/epub2tts.py", line 168, in __init__
    ) = self.model.speaker_manager.speakers[self.config['speaker']].values()
AttributeError: 'NoneType' object has no attribute 'speakers'
```

**Comment by calledit** [comment]
That might/should fix it.

**Comment by aedocw** [comment]
New error - progress! 

```
ᐅ python3 epub2tts.py /tmp/testing.txt --xtts voices/adam-1.wav --model adamwhite --cover cover.jpg
[...]
Traceback (most recent call last):
  File "/home/doc/epub2tts.py", line 1145, in <module>
    main()
  File "/home/doc/epub2tts.py", line 1132, in main
    mybook.read_book(
  File "/home/doc/epub2tts.py", line 776, in read_book
    engine_cl = XTTS(config)
  File "/home/doc/epub2tts.py", line 163, in __init__
    ) = self.model.get_conditioning_latents(audio_path=self.voice_samples)
AttributeError: 'XTTS' object has no attribute 'voice_samples'
```

**Comment by calledit** [comment]
That should probably fix that. :)

**Comment by aedocw** [comment]
Working now!

**Pull request merged**
