### PR TITLE
Multiprocessing

### PR DESCRIPTION
**Pull request by calledit**
PR that adds parallel execution.
Where each chapter gets it own process.

Just did a 7 hour audiobook in 9 minutes on my MacBook using 16 threads.
Using the new --threads argument

### CODE REVIEW

**Comment by aedocw** [comment]
That's excellent! What engine are you using, what's an example command? Would need an update to README for that, plus a version bump in setup.py.

I tried with my usual tests (using text file instead of epub since I just want to try very short amount of text to validate different features work), and got the following:

```
ᐅ python3 epub2tts.py /tmp/testing.txt --cover cover.jpg
[...]
Traceback (most recent call last):
  File "/home/doc/epub2tts.py", line 1187, in <module>
    main()
  File "/home/doc/epub2tts.py", line 1174, in main
    mybook.read_book(
  File "/home/doc/epub2tts.py", line 894, in read_book
    chapter_job_que.append(({'config': config, 'tempfiles': tempfiles, 'sentene_job_que': sentene_job_que, 'outputwav': outpu
twav, 'chapter': self.section_names[i].strip()}))
IndexError: list index out of range
```

**Comment by calledit** [comment]
God that you tested that thing!
Should work now.

**Comment by calledit** [comment]
Default for --threads is 16

Which is probably unnecessarily high if you are using xtts, but about right for edge.

**Comment by aedocw** [comment]
Testing with vits, `python3 epub2tts.py /tmp/testing.txt --cover cover.jpg` hangs at `initialization of speaker-embedding layers`, though I'm not really sure why. Edge worked fine. XTTS did not work though (this is Ubuntu 22.04 in Windows WSL, which works great with main release). Here's what I got:
```
[...]
initiating chapter:  Part 1
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/doc/epub2tts.py", line 327, in process_book_chapter
    tts_engine = dat['config']['engine_cl'](dat['config'])
  File "/home/doc/epub2tts.py", line 146, in __init__
    and torch.cuda.get_device_properties(0).total_memory > 3500000000
  File "/home/doc/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 449, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/doc/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
"""
```

**Comment by calledit** [comment]
Mabye vits is failing cause you are running out of memory, and it is starting to swap.
Would be interesting to see if lowering --threads to 2 works better.
Vits was fine for me in my tests but I only tested a short book with 2 chapters.

Maybe we should set default --threads to something lower if this is an issue.

**Comment by aedocw** [comment]
Default threads should probably be 2, since a lot of users that I've helped with issues have lower end equipment, feels better to default to assuming minimal case. We can make it really prominent in the instructions to experiment with more threads if your system can handle it.

I tried with threads 2 and 1 and it worked, but it's not cleaning up the intermediate files I think. After one run, "testing-1.wav" still exists so it skips that, then hits errors.

**Comment by calledit** [comment]
New default is now 2 threads and I fixed the cleanup of temp files bug.

**Comment by aedocw** [comment]
More progress! But I hit the following:
```
ᐅ python epub2tts.py /tmp/testing.txt
[...]
[concat @ 0x55dc09c90340] Impossible to open 'testing-1.wav'      
filelist.txt: No such file or directory                     
Traceback (most recent call last):                          
  File "/home/doc/epub2tts.py", line 1178, in <module>      
    main()                    
  File "/home/doc/epub2tts.py", line 1165, in main          
    mybook.read_book(         
  File "/home/doc/epub2tts.py", line 953, in read_book      
    self.generate_metadata(files)
  File "/home/doc/epub2tts.py", line 419, in generate_metadata    
    duration = self.get_duration(file_name)                 
  File "/home/doc/epub2tts.py", line 432, in get_duration   
    audio = AudioSegment.from_file(file_path)               
  File "/home/doc/.local/lib/python3.10/site-packages/pydub/audio_segment.py", line 651, in from_file                   
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)                                              
  File "/home/doc/.local/lib/python3.10/site-packages/pydub/utils.py", line 60, in _fd_or_path_or_tempfile              
    fd = open(fd, mode=mode)  
FileNotFoundError: [Errno 2] No such file or directory: 'testing-1.wav'
```

**Comment by calledit** [comment]
maybe now

**Comment by aedocw** [comment]
With the same test (just python epub2tts.py sometext.txt), it looks like filelist.txt is empty at the point where it's trying to build the audiobook. I think it's not creating any intermediate audio files (adding --debug, none of the temp files are there).

**Comment by calledit** [comment]
I think I fixed that thing now.
Got a very similar error message as the one you posted before I fixed the bug.

**Comment by aedocw** [comment]
More excellent progress! Vits and edge working great! XTTS not working though, got this error:
```
ᐅ python3 epub2tts.py /tmp/testing.txt --threads 1  --engine xtts --speaker "Damien Black" --cover cover.jpg
[...]
Traceback (most recent call last):                                
  File "/home/doc/epub2tts.py", line 1183, in <module>            
    main()                       
  File "/home/doc/epub2tts.py", line 1170, in main                
    mybook.read_book(            
  File "/home/doc/epub2tts.py", line 897, in read_book            
    map_result = list(map(process_book_chapter, chapter_job_que))                                                                   
  File "/home/doc/epub2tts.py", line 325, in process_book_chapter                                                                   
    tts_engine.proccess_text_retry(text, file_name)               
  File "/home/doc/epub2tts.py", line 72, in proccess_text_retry                                                                     
    ratio, result_text = self.compare(text, wave_file_name)       
AttributeError: 'XTTS' object has no attribute 'compare' 
```

**Comment by calledit** [comment]
Should be fixed now.

**Comment by aedocw** [comment]
Close!

```
ᐅ python3 epub2tts.py /tmp/testing.txt --threads 1  --engine xtts --speaker "Damien Black" 
Traceback (most recent call last):
  File "/home/doc/epub2tts.py", line 50, in <module>
    class Text2WaveFile:
  File "/home/doc/epub2tts.py", line 51, in Text2WaveFile
    self.whispermodel = None
NameError: name 'self' is not defined
```

**Comment by calledit** [comment]
There you go

**Comment by aedocw** [comment]
Thanks again for all your work to improve this, I think it's super close!

Looks like the something gets missed when it's comparing output with whisper and has to try again, here's what I got:

```
# head -n 10 README.md > /tmp/testing.txt
# python3 epub2tts.py /tmp/testing.txt --threads 1  --engine xtts --speaker "Damien Black"
[...]
Spoken text did not sound right after control with whisper - 83
Input: > epub2tts is a free and open source python app to easily create a full-featured audiobook from an epub or text file using realistic text-to-speech from Coqui AI TTS(https, //github.com/coqui-ai/TTS), OpenAI or MS Edge.
Output:  AppuptWatz is a free and open source Python app to easily create a full featured audiobook from an app hub or text file using realistic text to speech from cockiei-tts. Getitp.com cockiei-tts. Open i or miss inch.
Spoken text did not sound right after control with whisper - 87
Input: > epub2tts is a free and open source python app to easily create a full-featured audiobook from an epub or text file using realistic text-to-speech from Coqui AI TTS(https, //github.com/coqui-ai/TTS), OpenAI or MS Edge.
Output:  DE pooped wats is a free and open source python app to easily create a full featured audiobook from an e-pub or text file using realistic text to speech from kokeuaiitts dtts dthub.com kokeuaiitts openai or ms edge
Traceback (most recent call last):
  File "/home/doc/epub2tts.py", line 1189, in <module>
    main()
  File "/home/doc/epub2tts.py", line 1176, in main
    mybook.read_book(
  File "/home/doc/epub2tts.py", line 903, in read_book
    map_result = list(map(process_book_chapter, chapter_job_que))
  File "/home/doc/epub2tts.py", line 340, in process_book_chapter
    tts_engine.proccess_text_retry(text, file_name)
  File "/home/doc/epub2tts.py", line 94, in proccess_text_retry
    print(f"Something is wrong with the audio acording to whisper ({ratio}): {tempwav}")
NameError: name 'tempwav' is not defined
```

**Comment by calledit** [comment]
Fixed

**Comment by aedocw** [comment]
This works great, huge improvement to the code base, thank you!

Could you comment on `--threads X`, and what folks should know when deciding how many threads to try? Or is it really just a matter of "depending on how much memory you've got available, you may be able to run many threads, you'll have to experiment with your system to see"? LMK if that's the case, I can merge this then update the README and setup.py.

**Comment by calledit** [comment]
If you are using edge or openai you can more or less use as many threads as you have chapters.
If you are using TTS or XTTS, experiment to see what works best.

**Pull request merged**
