### PR TITLE
Adding .srt support

### PR DESCRIPTION
**Pull request by calledit**
Would be nice to be able to view the text sentence by sentence as it is spoken.

One way to save such data is a .srt file.

This PR intends to add .srt file support to epub2tts.

Things to do:

- [x] Save timings for all sentences in each chapter in to temp files
- [x] Correct the timings for silence removal. (or disable silence removal)
- [x] Concatenate all the individual temp timing chapter files in to a final big .srt file

### CODE REVIEW

**Comment by calledit** [comment]
This should be good for people wanting to read along with the audio as mentioned in: https://github.com/aedocw/epub2tts/issues/276

**Comment by calledit** [comment]
To view the result you can use VLC

You can open the .m4b file in vlc.
Activate "Audio > Visualizations > Spectrometer"
Then go to subtitles and select the .srt file.

Now you will get a voice reading the book with a spectrometer visualisation and subtitles.

**Comment by calledit** [comment]
This can be merged now.

**Comment by aedocw** [comment]
This looks pretty rad, thanks! I will try to find time to play with it this weekend.

One thing though, this definitely warrants a version bump in setup.py. Can you give this version 2.7.0?

**Pull request merged**
