### PR TITLE
Added functionality in the export() automatically get the cover image of the book

### PR DESCRIPTION
**Pull request by erfansamandarian**
Added functionality in the export() to automatically get the book's cover image and save it as the name of the book + .png.

### CODE REVIEW

**Review by aedocw — COMMENTED** [review]
This looks great, EXCELLENT addition, thank you so much!

As soon as I have a chance to test this I'll merge it.

**Comment by aedocw** [comment]
Thanks for this work, I copied this into epub2tts-edge, it's brilliant! https://github.com/aedocw/epub2tts-edge/pull/17

**Comment by erfansamandarian** [comment]
You're too kind Chris. Thank you for starting epub2tts, it's a great project. Once I've finished writing my uni assignment, I'll be sure to try to help out some more where I can.

**Comment by aedocw** [comment]
No problem, and good luck with your assignment - take care!

**Pull request merged**
